contributors.txt
Añadiendo el archivo contributors.txt para facilitar acceso de los contactos que contribuyen en este proyecto
=> Añadir contributors.txt

README.md
Cambios:
- Actualizado el Readme para incluir la configuración que nos funciona a todos.
=> Add github ssh keys and git config file

contributors.txt
- Añadiendo a JJ a nuestro archivo contributors
=> Añadir a Jonathan a contributors.txt

contributors.txt
Cambios:
- Añadir el correo de Ale
=> Añadir a Javier a contributors.txt

contributors.txt
- Añadiendo a jp a nuestro archivo contributors
=> Añadir a Juan a contributors.txt

contributors.txt
Añadir a Maria a contributors.txt
=> Anadir a Maria a contributors.txt

sample_website/index.html
=> resuelva exercises 2.2.3

sample_website/tags.html
=> realice ejercicio 3.1.1

sample_website/tags.html
En este ejercicio se añadieron a la tabla que ya teníamos en el campo de Inline Elements las tags: strong, a, img y code.
=> Realice ejercicio 3.2.3

sample_website/index.html, sample_website/moby_dick.html, sample_website/tags.html
Se añadió los enlaces del menú a cada una de las paginas (Index, Tags y Moby Dick).
=> Hacer ejercicio 3.5.1

sample_website/tags.html
=> Añada etiquetas <ol>, <ul>, y <li> a tags.html

sample_website/index.html, sample_website/moby_dick.html, sample_website/tags.html
Añadiendo etiquetas header, div y span a las tablas en tags.html
=> exercises 3.3.1

sample_website/index.html
Se agrego una cita en bloque en index.html con relleno (padding) y color de fondo (background)
=> Hacer ejercicio 4.5.1.2

sample_website/css/main.css, sample_website/index.html, sample_website/moby_dick.html, sample_website/tags.html
- Se añadió una clase llamada "image-link" en la pagina home
- Se añadió el menu actualizado a las paginas faltantes (moby.dick y tags.html)
- Se movieron todas las reglas de estilo que existían en tags.html y Moby.dick a main.css y se comprobó que la pagina no presenta diferencia (que es lo que debe ocurrir)
- Se agrego un id a la etiqueta <h2> Funders </h2>
=> Hacer ejercicio 4.7.3

sample_website/css/main.css, sample_website/index.html, sample_website/moby_dick.html, sample_website/tags.html
- Se eliminó el subrayado para los links internos y cambios automaticos de color al visitar dichos links.
- Se agregó una nueva tabla con información de algunos tags del documento (html, head, body, title, y meta).
=> Realice ejercicio 4.6.1

sample_css/index.html
1 Cambie el color de los enlaces dentro del lis.
2 Añada un borde alrededor del li usando el mismo estilo que usamos para añadir los bordes alrededor de los divs.
=> exercise 5.4.1

sample_css/index.html
Clase donde agregamos un id y estilos al mismo.
=> clase 12 de abril

sample_css/index.html
Se agrego a la sección de estilo un nuevo id CSS y una nueva clase.
=> Hacer ejercicio 5.5.1

sample_css/index.html
=> Clase 14 de abril

sample_css/index.html
Esta es la clase del dia 
- Se removio el resultado de la tarea pasada porque era solo para ver el efecto
- Se añadio el uso de rgba y un repaso de colores hexadecimales
=> clase del 17 de abril

sample_css/index.html
- Se cambiaron los links de declaraciones "a" a un color morado claro con valor hexadecimal
- Se cambiaron las palabra de colores por su equivalente en valor hexadecimal
- Por medio de rgba se le coloco opacidad del 20% a los primeros links de la pagina
- Se le añadió a los primeros link la clase .social-link
=> Hacer ejercicio 7.1.3

sample_css/index.html
Clase del dia con los cambios usando em para font-size
=> clase del 19 de Abril

sample_css/index.html
1 Establezca el tamaño de fuente de .bio-box en 48px
2 Establezca el relleno .bio-box a un tamaño de píxel de 20px
=> exercises 7.5.1

sample_css/index.html
Clase del dia subida para poder hacer la tarea del dia
=> Clase del 25-04-2023

sample_css/index.html
=> clase del 26-04-2023

sample_css/index.html
Se realizo hasta el capitulo 8.7
=> Clase 27 abril

README.md, sample_jekyll/_layouts/default.html, sample_jekyll/_layouts/test.html, sample_jekyll/index.html, sample_jekyll/tested.html
- Jekyll en un nuevo folder llamado sample_jekyll
- se hizo el ejercicio de la seccion
- Se añadio un TODO
=> clase 05-05-2023

.editorconfig, README.md, sample_jekyll/_layouts/default.html, sample_jekyll/_layouts/test.html, sample_jekyll/css/main.css, sample_jekyll/index.html, sample_jekyll/tested.html
Cambios:
- Se movio todo el contenido css desde el layout hacia un directorio css
- Se creo un archivo llamado main.css y alli se colocaron todos los styles
- Debido a que otra persona puede usar otro editor se creo un .editorconfig para mantener uniformidad de formato sin importar la configuracion del editor
- Para que `.editorconfig` funcione debemos instalar el plugin en visual studio code tome la oportunidad de colocar todos los plugins en el `README.md`
=> Clase del dia 08-05

sample_jekyll/_includes/head.html, sample_jekyll/_layouts/default.html
- `_includes` folder creado
- `head.html` añadido como primer include
[clase](https://youtu.be/MXjpEu9ojVI)
=> clase del dia 9 Mayo

.prettierrc.json, README.md, sample_jekyll/_includes/header.html, sample_jekyll/_layouts/default.html, sample_jekyll/css/main.css
Cambios:
- Añadir nuevo include `header.html`
- Editar los estilos del header
- Incluir el nuevo include en nuestro page
- Añadir configuracion de prettier `.prettierrc.json` para respetar los espacios de Markdown y no me causen problemas con mi linter
link de la clase: https://youtu.be/CJPqbYUrnn4
=> clase del dia Wed May 10 06:15:13 2023

sample_jekyll/_layouts/default.html, sample_jekyll/css/main.css
Cambios:
- Selectores de hijos y hermanos
video: https://youtu.be/_GY6N1iABg8
=> clase del Thu May 11 06:15:00 2023

sample_jekyll/_includes/footer.html, sample_jekyll/_includes/header.html, sample_jekyll/_includes/nav-links.html, sample_jekyll/_layouts/default.html, sample_jekyll/css/main.css
Clase del 25 de mayo 2023
- Añadido nuevo footer
- Creando un include que se incluirá en otros includes 
-  Extraídos styles en común entre header y footer
=> Finish initial layout

README.md, learn_enough_js_tutorial/index.html
- Actualizar el README.md
- Crear un nuevo directorio para nuevo curso js
- Nuestro primer script
=> Clase del dia 30 may

README.md
Actualice readme con instrucciones para instalar nvm
=> Clase del dia 01-06 

learn_enough_js_tutorial/hello, learn_enough_js_tutorial/hello.js
- Se adicionaron dos archivos con codigo js
- `hello` es un shell script
-  `hello.js` es un file js para ser ejecutado con node
=> Primeros archivos js

.github/pull_request_template.md
- Nuevo folder `.github` añadido
- nuevo file `.github/pull_request_template.md`
=> Añada pull request template

sample_jekyll/_includes/nav-links.html, sample_jekyll/css/main.css, sample_jekyll/gallery/index.html, sample_jekyll/gallery/test.html
- Cambios en main.css que mejoran la pagina 
- creacion de un nuevo folder llamado `gallery`
- dos nuevos html: index.html y test.html
Nota: eliminar test.html y nav4 en los nav-links
=> Mejorar el index.html y añadir una nueva pagina

sample_jekyll/_includes/nav-links.html, sample_jekyll/_posts/2016-11-03-title-of-post.md, sample_jekyll/blog/index.html, sample_jekyll/css/main.css
En este nuevo capitulo comenzamos con la creacion de una nueva pagina blog.
No hemos terminado el capitulo pero ya hay tareas asi que lancemos el primer PR
- Añadido una nueva pagina en `blogs` en un archivo `index.html`
- Añadido una entrada para blogs en `nav` bar
- Añadido `sample_jekyll/_posts/2016-11-03-title-of-post.md`
- Cambio de clases css
=> feature(html-css): Anexe una nueva pagina de blogs

sample_jekyll/_includes/head.html, sample_jekyll/_includes/nav-links.html, sample_jekyll/_layouts/post.html, sample_jekyll/css/main.css, sample_jekyll/index.html
Cada vez que demos clic en el link de cada post nos llevara a la pagina perse del post
- Añadido el layout `post.html` que a su vez usa el `default.html`
- Ajustadas las rutas del css por problemas con estos nuevos posts
- Editado el post layout para renderizar cada post
- Añadidos los estilos en `main.css`
- Añadido primer post en nav links y tambien en home page
=> Paginas de posts

sample_jekyll/index.html
Se reparo un error encontrado en los urls
- Ajustado url en el index
=> fix (jekyll): Repare malos urls en html

Gemfile.lock, sample_jekyll/_includes/post-excerpt.html, sample_jekyll/blog/index.html, sample_jekyll/index.html
Se refactorizo el sitio moviendo la lista de publicaciones recientes a su propia inclusión y  cargando esa inclusión tanto en el índice del blog como en las páginas de detalles.
=> exercises 12.3.1 ejercicio 1

sample_jekyll/_includes/head.html, sample_jekyll/css/main.css
Cubriendo el capitulo del libro que permite que nuestra pagina web mute cuando se ve desde un dispositivo movil.
- El menu `nav` ahora muta de tamaño y separaciones
- ` .post-aside` desaparace acorde al tamaño de la pantalla del dispositivo
- `  .home-callout` se muestra ahora de manera vertical en pantallas pequeñas
=> feat(mobile): Anexando cambios mobile

README.md
- Se añadieron los siguientes métodos para modificar los arrays: slice, length,  includes, reverse, sort y toSorted
=> Agregar a README primeros metodos para array

learn_enough_js_tutorial/count.js
Contador de palabras
- Añadido un ejemplo de codigo que cuenta palabras en un texto
=> Contador de palabras

sample_jekyll/css/main.css, sample_jekyll/index.html
- Reparado error de footer 
- Prototipo mobile añadido
=> Clases de csss

sample_jekyll/_includes/header.html, sample_jekyll/_includes/nav-links.html, sample_jekyll/css/main.css
En las ultimas clases se ha editado el menu para ser interactivo y cambiar su interación dependiendo del dispositivo
- Añadido dropdown
- Modificada la interacción con el menu dependiendo del dispositivo
- nav dinamico con efectos animados
=> Clases CSS

sample_jekyll/_includes/nav-links.html, sample_jekyll/css/main.css
Este PR busca corregir los problemas encontrados
- Reparar tag mal cerrada
- ocultar el checkbox y label. Solo mostrarlo cuando es resolucion menor a 800px (esto ya esta hecho en @media)
=> fix(nav-links): Repare checkbox y tag mal cerrada

README.md, learn_enough_js_tutorial/count_with_map.js, learn_enough_js_tutorial/day.js, learn_enough_js_tutorial/index.html, learn_enough_js_tutorial/palindrome.js
- Dandole estilo al readme
- Resolviendo ejercicio 4.5.2
- Funciones en js descritas en README 
- Importar codigo definido en otros archivos
=> classroom Js

learn_enough_js_tutorial/exercises/exercise_5.3.2.js
Se escribió una función llamada emailParts para devolver un array del nombre de usuario y dominio para una dirección de correo electrónico estándar con el formato username@example.com
- Se agrego un directorio llamado exercises donde incluiremos las tareas de jv de ahora en adelante, aqui se agrego el archivo de este ejercicio "exercise_5.3.2"
- Ver los primeros minutos de la clase de hoy
=> Hacer ejercicio 5.3.2

README.md, learn_enough_js_tutorial/foreach.js
In this PR you can see how to use foreach
- Added `foreach.js`
- Documented how to iterate with a non-traditional C or C++ style
=> feat(foreach): Add other forms to itereate

sample_jekyll/_includes/head.html, sample_jekyll/css/main.css, sample_jekyll/index.html
Se realizo la tarea 14.1.3
- Se agregaron los iconos de twitter (que debería ya ser el de X jaja)
- Se añadio una fuente de Google Font a bio-box h3
Antes: 
Después:
=> Hacer ejercicio 14.1.3

learn_enough_js_tutorial/exercises/exercise_5.4.1.js, learn_enough_js_tutorial/exercises/exercise_6.1.1.js, learn_enough_js_tutorial/exercises/exercise_6.2.1.js
Se realizaron los ejercicios pendientes de javascript
=> Hacer ejercicios 5.4.1, 6.1.1 y 6.2.1 de js

README.md, learn_enough_js_tutorial/functional.js, learn_enough_js_tutorial/palindrome.js
This PR is meant to follow the Chapter of learn enough that addresses this topic (Cap. 6)
- Added `learn_enough_js_tutorial/functional.js`
- constructor Function and objects
=> functional programming

learn_enough_js_tutorial/exercises/exercise_6.3.4.js
Se realizo la parte uno de del ejercicio 6.3.4 que consistía en hacer una función que devuelva el producto de todos los elementos de una matriz por medio del método reduce.
=> Hacer parte 1 ejercicio 6.3.4·

learn_enough_js_tutorial/exercises/exercise_7.1.1.js
Se realizo ejercicio 7.1.1 donde se pedia agregar un método Louder al objeto Phrase que obtuviese como resultado el contenido en mayúscula.
=> Hacer ejercicio 7.1.1

learn_enough_js_tutorial/palindrome.js
This PR includes objects and all the concepts related.
- Added `Phrase` class
- Added `TranslatedPhrase` class that inherintance from `Phrase` class
=> feat(js): Objects

README.md, learn_enough_js_tutorial/exercises/exercise_7.3.1.js
- Se agrego un método llamado blank al prototipo del objeto String que devuelve verdadero si la cadena está vacía o consta únicamente de espacios en blanco (espacios, tabulaciones o nuevas líneas). Se uso para esto expresiones regulares. 
Queda pendiente la segunda parte del ejercicio que no fui capaz de resolverla
=> Hacer ejercicio 7.3.1

README.md, learn_enough_js_tutorial/palindrome/README.md, learn_enough_js_tutorial/palindrome/index.js, learn_enough_js_tutorial/palindrome/package.json, learn_enough_js_tutorial/palindrome/test/test.js
In this PR we are going to cover everything that the book learn enough covers in its chapter 8(TDD)
- Updated README
- Create a new module `palindrome`
- Create our first `package.json`
No risk detected so far
N/A
N/A
N/A
=> TDD chapter 8

README.md, sample_jekyll/grid-landing.html, sample_jekyll/grid.html
This PR is more focused on covering advanced features that the book will describe in the rest of the chapter
=> feat(css): Evaluating advance grid features

.gitignore, README.md, learn_enough_js_tutorial/examples/ch10/package-lock.json, learn_enough_js_tutorial/examples/ch10/package.json, learn_enough_js_tutorial/examples/ch10/palindrome_file, learn_enough_js_tutorial/examples/ch10/phrases.txt
- How to read/write in a txt file
- create a file with palindromes found in another file
=> JS: Chapter 10

README.md, learn_enough_js_tutorial/examples/ch10/exercises/10.2.1.palindrome_url, learn_enough_js_tutorial/examples/ch10/package-lock.json, learn_enough_js_tutorial/examples/ch10/package.json, learn_enough_js_tutorial/examples/ch10/palindrome_url, learn_enough_js_tutorial/examples/ch10/wikp
- Added wikp script to get <p> from Wikipedia
- Solved Exercise 10.2.1
- Fixed typo in docs
- Added script to Pull content from the internet and find palindromes
=>  js(Chapter 10)

README.md
- Compra de dominios y configuracion
=> docs(css): Update readme

README.md
=> docs: update readme with github config
